### ISSUE TITLE
users route

### ISSUE THREAD

**Issue by cpb2948** [badleyy/rtapi#7]
@dadleyy 

The routes

```
GET - users/1
```

```
GET - users/1/product
```

do we need to include the 1 parameter in the route? We will be pulling the user id from either the session or the JWT token. I feel like it belongs there, but im not sure we need it.

**Comment by dadleyy** [comment]
we should have a user lookup route - `/users/{user_id}`. that would not be used too too much but if we want like gravatars or something like that, we'll want consumers to be able to look up most users. 

just to be clear, the `/users` route _doesn't return the current user_. it returns a list of users based on query parameters - 

```
GET /users?filters[name]=danny
```

or something. The route to get the current user would either be

```
GET /auth

or

GET /session
```

to your point about getting a user's products, I think we should avoid "subresource" routes. I'd rather build out an intuitive query interface for our "index" routes - 

```
GET /products?user=24
GET /raffles?ending=soon
GET /media?raffle=1
```

**Comment by cpb2948** [comment]
we could do that. My only thought is it just takes away the power from laravel's route engine. We would have to parse the query string ourselves and do "routing" ourselves.

eg 

```
/products?user=24

if(Input::has('user') {
    GetUsersProducts();
}
if(input::has('all') {
    GetAllProducts();
}

etc
```

As opposed to just using routes

```
/users/24/products

GetUsersProducts();

/products

GetAllProducts();
```

**Comment by cpb2948** [comment]
but for implementing filters the query string makes sense to me.

```
Get - /users/24/products?ending=soon
```

**Comment by dadleyy** [comment]
I wonder if we could build out a query string parser that could generate an array to send into Eloquent's `where` function for us...

``` php
class UserController extends BaseController {
  public function search() {
    $query = this->generateQuery();
    // $query is now:
    // array(
    //  array("name", "=", "danny"), 
    //  array("email", "=", "...")
    // )
    $users = Users::where($query);  
    ...
  }
}
```

**Comment by cpb2948** [comment]
that's a good idea. We can implement that in middleware to use it across all the routes
